using System;

namespace NsqSharp.Bus
{
    /// <summary>
    /// Information about the message being handled.
    /// </summary>
    public interface ICurrentMessageInformation
    {
        /// <summary>A unique identifier for this instance of handling this message generated by NsqSharp.</summary>
        Guid UniqueIdentifier { get; }
        /// <summary>The topic the message was delivered on.</summary>
        string Topic { get; }
        /// <summary>The channel the message was delivered on.</summary>
        string Channel { get; }
        /// <summary>The message.</summary>
        Message Message { get; }
    }
}
